# Generated by Django 4.2.5 on 2023-09-10 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='MobileNets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('image_url', models.CharField(max_length=2083)),
                ('img_alt', models.CharField(max_length=255)),
                ('destination_url', models.CharField(max_length=2083)),
            ],
        ),
        migrations.CreateModel(
            name='Datas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.CharField(max_length=2083)),
                ('img_alt', models.CharField(max_length=255)),
                ('destination_url', models.CharField(max_length=2083)),
                ('data_price', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CoreApp.dataprice')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CoreApp.mobilenets')),
            ],
        ),
        migrations.AddField(
            model_name='dataprice',
            name='mobile_nets',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CoreApp.mobilenets'),
        ),
    ]
